$(function() {
    var medications = [
        "Accolate - Zafirlukast",
        "Accuhaler - Salbutamol",
        "Accupro - Quinapril",
        "Acepril - Captopril",
        "Acetaminophen - Paracetamol",
        "Achromycin - Tetracycline",
        "Acupan - Nefopam hydrochloride",
        "Adactone - Spironolactone",
        "Adalat - Nifedipine",
        "Adizem - Diltiazem",
        "Adrenaline in dental local anaesthetic solutions - Epinephrine",
        "AeroBec - Beclometasone dipropionate",
        "Aerocrom - Sodium cromoglicate",
        "Aerolin - Salbutamol",
        "Airomir - Salbutamol",
        "Akineton - Biperiden",
        "Aldomet - Methyldopa",
        "Algicon - Alginates",
        "Alkeran - Melphalan",
        "Allegron - Nortriptyline",
        "Alphaparin - Certoparin",
        "Alu-cap - Aluminium hydroxide",
        "Alupent - Orciprenaline sulphate",
        "Alvercol - Alverine citrate",
        "Amaryl - Glimepiride",
        "Ametop - Amethocaine",
        "Amias - Candesartan",
        "Amikin - Amikacin",
        "Amoxil - Amoxicillin",
        "Amylobarbitone - Amobarbital",
        "Anabact - Metronidazole",
        "Anafranil - Clomipramine hydrochloride",
        "Ancotil - Flucytosine",
        "Androcur - Cyproterone acetate",
        "Anexate - Flumazenil",
        "Angiopine - Nifedipine",
        "Angitil - Diltiazem",
        "Anquil - Benperidol",
        "Antabuse - Disulfiram",
        "Antepsin - Sucralfate",
        "Anturan - Sulfinpyrazone",
        "Apresoline - Hydralazine",
        "Aprovel - Irbesartan",
        "Aricept - Donepezil hydrochloride",
        "Arimidex - Anastrozole",
        "Arosmasin - Exemestan",
        "Arpicolin - Procyclidine hydrochloride",
        "Arythmol - Propafenone hydrochloride",
        "Asacol - Mesalazine",
        "Asendis - Amoxapine",
        "AsmaBec - Beclometasone dipropionate",
        "Asmasal - Salbutamol",
        "Aspirin - Acetylsalicylic acid",
        "Atarax - Hydroxyzine hydrochloride",
        "Atrovent - Ipratropium bromide",
        "Augmentin - Co-amoxiclav",
        "Augmentin-Duo - Co-amoxiclav",
        "Avloclor - Chloroquine",
        "Avomine - Promethazine teoclate",
        "Axid - Nizatidine",
        "Azactam - Aztreonam",
        "Azopt - Brinzolamide",
        "BCNU - Carmustine",
        "Bambec - Bambuterol hydrochloride",
        "Baratol - Indoramin",
        "Baxan - Cefadroxil",
        "Becloforte - Beclometasone dipropionate",
        "Becodisks - Beclometasone dipropionate",
        "Beconase - Beclometasone dipropionate",
        "Becotide - Beclometasone dipropionate",
        "Benadryl allergy relief - Acrivastine",
        "Benemid - Probenecid",
        "Berotec - Fenoterol hydrobromide",
        "Beta-cardone - Sotalol hydrochloride",
        "Betadine - Povidone-iodine",
        "Betaloc - Metoprolol",
        "Betnesol - Betamethasone",
        "Bicillin - Procaine penicillin/Procaine benzylpenicillin",
        "Bioplex - Carbenoxolone sodium",
        "Bioral gel - Carbenoxolone sodium",
        "Biorphen - Orphenadrine hydrochloride",
        "Bocasan - Sodium perborate",
        "Bonefos - Sodium clodronate",
        "Botox - Botulinum A Toxin",
        "Bricanyl - Terbutaline sulphate",
        "BritLofex - Lofexadine hydrochloride",
        "Britaject - Apomorphine hydrochloride",
        "Broflex - Benzhexol hydrochloride/ Trihexyphenidyl hydrochloride",
        "Bronchodil - Reproterol hydrochloride",
        "Brufen - Ibuprofen",
        "Buccastem - Prochlorperazine",
        "Budenofalk - Budesonide",
        "Burinex - Bumetanide",
        "Buscopan - Hyoscine butylbromide",
        "Buspar - Buspirone hydrochloride",
        "Butacote - Phenylbutazone",
        "Butobarbitone - Butobarbital",
        "Cabaser - Cabergoline",
        "Cafegot - Ergotamine tartrate",
        "Calcitare - Calcitonin-porcine",
        "Calcort - Deflazacort",
        "Calicard - Diltiazem",
        "Calpol - Paracetamol",
        "Calsynar - Salcatonin",
        "Camcolit - Lithium salts",
        "Campral EC - Acamprosate calcium",
        "Campto - Irinotecan hydrochloride",
        "Capastat - Capreomycin",
        "Capoten - Captopril",
        "Cardene - Nicardipine",
        "Cardura - Doxazosin",
        "Catapres - Clonidine",
        "Cefrom - Cefpirome",
        "Cefzil - Cefprozil",
        "Celance - Pergolide",
        "Celebrex - Celecoxib",
        "Celevac - Methylcellulose",
        "Cellcept - Mycophenolate mofetil",
        "Ceporex - Cefalexin",
        "Cerubidin - Daunorubicin",
        "Chirocain - Levobupivacaine",
        "Chloral elixir - Chloral hydrate",
        "Chloral mixture - Chloral hydrate",
        "Chlorohex - Chlorhexidine gluconate",
        "Chloromycetin - Chloramphenicol",
        "Cidomycin - Gentamicin",
        "Cinobac - Cinoxacin",
        "Cipramil - Citalopram",
        "Ciproxin - Ciprofloxacin",
        "Citanest - Prilocaine",
        "Claforan - Cefotaxime",
        "Clarityn - Loratadine",
        "Clexane - Enoxaparin",
        "Clinoril - Sulindac",
        "Clomid - Clomifene",
        "Clopixol acuphase - Zuclopenthixol acetate    ",
        "Clopixol conc.  ? Zuclopenthixol decanoate",
        "Clopixol - Zuclopenthixol decanoate",
        "Clotam - Tolfenamic acid",
        "Clozaril - Clozapine",
        "Co-danthromer - Dantron",
        "Co-danthrusate - Dantron",
        "Cogentin - Benzatropine mesilate",
        "Colazide - Balsalazide sodium",
        "Colestid - Colestipol hydrochloride",
        "Colofac - Mebeverine hydrochloride",
        "Colomycin - Colistin",
        "Colpermin - Peppermint oil",
        "Comtess - Entacapone",
        "Concordin - Protriptyline hydrochloride",
        "Contraceptive Pill - Progestogen",
        "Convulex - Valproate",
        "Coracten - Nifedipine",
        "Cordarone - Amiodarone",
        "Corday - Nifedipine",
        "Cordilox - Verapamil",
        "Corfaretic - Nadolol",
        "Corsodyl - Chlorhexidine gluconate",
        "Cortisyl - Cortisone acetate",
        "Cosopt - Dorzolamide",
        "Cozaar - Losartan",
        "Creon - Pancreatin",
        "Crixivan - Indinavir",
        "Cromogen Easi-Breathe - Sodium cromoglicate",
        "Crystapen Penicillin V - Penicillin G",
        "Crystapen - Benzyl penicillin",
        "Cyklokapron - Tranexamic acid",
        "Cymevene - Ganciclovir",
        "Cystrin - Oxybutynin hydrochloride",
        "Cytosar - Cytarabine",
        "Cytotec - Misoprostol",
        "DDAVP - Desmopressin",
        "DF118 - Dihydrocodeine tartrate",
        "Daktarin - Miconazole",
        "Dalacin C - Clindamycin",
        "Dalmane - Flurazepam",
        "Daonil - Glibenclamide",
        "Daraprim - Pyramethamine",
        "De-Noltab - Tripotassium dicitratobismuthate",
        "Deca-Durabolin - Nandrolone",
        "Decadron - Dexamethasone",
        "Depixol Conc - Flupentixol decanoate",
        "Depixol Low Volume - Flupentixol decanoate",
        "Depixol - Flupentixol",
        "Depixol - Flupentixol decanoate",
        "Deseril - Methysergide",
        "Desmotabs - Desmopressin",
        "Destolit - Ursodeoxycholic acid",
        "Deteclo - Tetracycline",
        "Detrunorm - Propiverine hydrochloride",
        "Detrusitol - Tolterodine tartrate",
        "Dexedrine - Dexamfetamine sulphate",
        "Dialar - Diazepam",
        "Diamicron - Gliclazide",
        "Diazemuls - Diazepam",
        "Diconal - Dipipanone",
        "Diflucan - Fluconazole",
        "Dilzem - Diltiazem",
        "Dimetriose - Gestrinone",
        "Dimotane - Brompheniramine maleate",
        "Dioctyl - Docusate sodium",
        "Diovan - Valsartan",
        "Dipentum - Olsalazine sodium",
        "Diprivan - Propofol",
        "Disipal - Orphenadrine hydrochloride",
        "Diskhaler - Fluticasone propionate",
        "Distaclor MR - Cefaclor",
        "Distaclor - Cefaclor",
        "Distamine - Penicillamine",
        "Dixarit - Clonidine",
        "Docusol - Docusate sodium",
        "Dolmatil - Sulpiride",
        "Dolobid - Diflunisal",
        "Dostinex - Cabergoline",
        "Dozic - Haloperidol",
        "Dramamine - Dimenhydrinate",
        "Droleptan - Droperidol",
        "Dumicoat - Miconazole",
        "Durogesic - Fentanyl",
        "Duromine - Phentermine",
        "Dutonin - Nefazodone hydrochloride ",
        "Dyspamet - Cimetidine",
        "Dysport - Botulinum A Toxin",
        "Dytac - Triamterene",
        "Easi-breathe - Salbutamol",
        "Edronax - Reboxetine",
        "Efcortesol - Hydrocortisone",
        "Efexor - Venlafaxine",
        "Efudix - Fluorouracil",
        "Eldepryl - Selegeline hydrochloride",
        "Eldisine - Vindesine sulphate",
        "Eloxatin - Oxaliplatin",
        "Elyzol Flagyl - Metronidazole",
        "Emcor - Bisoprolol",
        "Emeside - Ethosuximide",
        "Emflex - Acemetacin",
        "Endoxana - Cyclophosphamide",
        "Entocort - Budesonide",
        "Epanutin - Phenytoin sodium",
        "Epilim - Valproate",
        "Epinephrine in dental local anaesthetic solutions - Adrenaline",
        "Epivir - Lamivudine",
        "Equagesic - Meprobamate",
        "Equasym - Methylphenidate hydrochloride",
        "Erymax - Erythromycin",
        "Erythrocin - Erythromycin",
        "Erythroped - Erythromycin",
        "Eskazole - Albendazole",
        "Estracyt - Estramustine phosphate",
        "Eucardic - Carvedilol",
        "Eudemine - Diazoxide",
        "Euglucon - Glibenclamide",
        "Evohaler - Salbutamol",
        "Exelon - Rivastigmine",
        "Famvir - Famciclovir",
        "Fansidar - Pyramethamine with Sulfadoxine",
        "Fasigyn - Tinidazole",
        "Faverin - Fluvoxamine maleate",
        "Feldene - Piroxicam",
        "Femara - Letrozole",
        "Fenbid - Ibuprofen",
        "Fenopron - Fenoprofen",
        "Fentazin - Perphenazine",
        "Feospan - Ferrous sulphate",
        "Ferrograd - Ferrous sulphate",
        "Fersaday - Ferrous fumarate",
        "Fersamal - Ferrous fumarate",
        "Fletcher's Enemette - Docusate sodium",
        "Flixonase - Fluticasone propionate",
        "Flixotide - Fluticasone propionate",
        "Florinef - Fludrocortisone acetate",
        "Floxapen - Flucloxacillin",
        "Fluanxol - Flupentixol",
        "Fludara - Fludarabine phosphate",
        "Foradil - Eformoterol fumarate/Formoterol fumarate",
        "Fortipine - Nifedipine",
        "Fortovase - Saquinavir",
        "Fortral - Pentazocine",
        "Fortum - Ceftazidime",
        "Fosamax - Alendronic acid",
        "Foscavir - Foscarnet sodium",
        "Fragmin - Dalteparin",
        "Frisium - Clobazam",
        "Froben - Flurbiprofen",
        "Fucidin - Sodium fusidate",
        "Fulcin - Griseofulvin",
        "Fungilin - Amphotericin",
        "Fungizone - Amphotericin",
        "Furadantin - Nitrofurantoin",
        "Furamide - Diloxanide furoate",
        "Fybogel - Ispaghula husk",
        "Fybogel - Mebeverine hydrochloride",
        "Gabitril - Tiagebine",
        "Galenphol - Pholcodine",
        "Galpseud - Pseudoephedrine hydrochloride",
        "Gamanil - Lofepramine",
        "Gastrobid Continus - Metoclopramide hydrochloride",
        "Gastrocote - Alginates",
        "Gastrocote - Aluminium hydroxide",
        "Gastrocote - Magnesium trisilicate",
        "Gastromax - Metoclopramide hydrochloride",
        "Gaviscon Maalox - Aluminium hydroxide",
        "Gaviscon - Alginates",
        "Gemzar - Gemcitabine",
        "Genotropin - Somatropin",
        "Genticin - Gentamicin",
        "Glandosane - Saliva substitute",
        "Glibenese - Glipizide    429",
        "Glucobay - Acarbose",
        "Glucophage - Metformin hydrochloride",
        "Glurenorm - Gliquidone",
        "Gopten - Trandolapril",
        "Grisovin - Griseofulvin",
        "Haldol decanoate - Haloperidol decanoate",
        "Haldol - Haloperidol",
        "Half Sinemet - Co-careldopa",
        "HeliClear - Lansoprazole",
        "Hemineverin - Clomethiazole",
        "Heroin hydrochloride - Diamorphine",
        "Hexopal - Nicotinic acid",
        "Hiprex - Methenamine",
        "Hivid - Zalcitabine",
        "Honvan - Fosfestrol tetrasodium",
        "Hormone Replacement Therapy - Oestrogen",
        "Human Mixtard - Biphasic isophane insulin",
        "Human Monotard - Insulin Zinc suspension",
        "Humatrope - Somatropin",
        "Humulin Lente - Insulin Zinc suspension",
        "Humulin - Soluble insulin",
        "Hycamtin - Topotecan",
        "Hydrocortone - Hydrocortisone",
        "Hygroton - Chlorthalidone",
        "Hypnovel - Midazolam",
        "Hypovase - Prazosin",
        "Hypurin - Soluble insulin",
        "Hytrin - Terazosin",
        "Ikorel - Nicorandil",
        "Ilosone - Erythromycin",
        "Imigran - Sumatriptan",
        "Imodium plus - Loperamide hydrochloride",
        "Imodium - Loperamide hydrochloride",
        "Imunovir - Inosine pranobex",
        "Imuran - Azathioprine",
        "Inderal - Propanolol",
        "Indocid - Indomethacin",
        "Innohep - Tinzaparin",
        "Innovace - Enalapril",
        "Insuman - Biphasic isophane insulin",
        "Intal - Sodium cromoglicate",
        "Invirase - Saquinavir",
        "Ionamin - Phentermine",
        "Isogel - Ispaghula husk",
        "Istin - Amlodipine besylate",
        "Kannasyn - Kanamycin",
        "Kaolin mixture - Kaolin",
        "Kefadim - Ceftazidime",
        "Kefadol - Cefamandole",
        "Keflex - Cefalexin",
        "Kefzol - Cefazolin",
        "Kemadrin - Procyclidine hydrochloride",
        "Kemicetine - Chloramphenicol",
        "Kenalog - Triamcinolone",
        "Kinidin - Quinidine",
        "Klaricid XL - Clarithromycin",
        "Klaricid - Clarithromycin",
        "Kolanticon - Dicyclomine hydrochloride/Dicycloverine hydrochloride",
        "Konsyl - Ispaghula husk",
        "Kytril - Granisetron",
        "Lamictal - Lamotrigine",
        "Lamisil - Terbinafine",
        "Lamprene - Clofazimine",
        "Lanoxin - Digoxin",
        "Lanvis - Tioguanine",
        "Largactil - Chlorpromazine hydrochloride",
        "Lariam - Mefloquine",
        "Lasix - Frusemide",
        "Lasma - Theophylline",
        "Lederfen - Fenbufen",
        "Ledermycin - Demeclocycline hydrochloride",
        "Lentaron - Formestane",
        "Lentizol - Amitriptyline hydrochloride",
        "Lescol - Fluvastatin",
        "Leukeran - Chlorambucil",
        "Leustat - Cladribine",
        "Lexotan - Bromazepam",
        "Librium - Chlordiazepoxide",
        "Lignospan - Lidocaine/ Lignocaine Dental preparations ",
        "Lignostab - Lidocaine/Lignocaine Dental preparations",
        "Limclair - Trisodium edetate",
        "Lingraine - Ergotamine tartrate",
        "Lipitor - Atorvastatin",
        "Lipobay - Cerivastatin",
        "Lipostat - Parvastatin",
        "Liskonum - Lithium salts",
        "Litarex - Lithium salts",
        "Lodine - Etodolac",
        "Lomotil - Co-phenotrope",
        "Loniten - Minoxidil",
        "Lopressor - Metoprolol",
        "Losec - Omeprazole",
        "Loxapac - Loxapine",
        "Luborant - Saliva substitute",
        "Ludiomil - Maprotiline hydrochloride",
        "Lustral - Sertraline",
        "MST - Morphine",
        "Maalox TC - Aluminium hydroxide",
        "Macrobid - Nitrofurantoin",
        "Macrodantin - Nitrofurantoin",
        "Madopar - Co-beneldopa",
        "Magnapen - Co-fluampicil",
        "Maloprim - Pyramethamine with Dapsone",
        "Malorone - Proguanil hydrochloride with Atovaquone",
        "Manerix - Moclobemide",
        "Manevac - Senna",
        "Marcain - Bupivacaine",
        "Maxalt - Rizatriptan",
        "Maxolon - Metoclopramide hydrochloride",
        "Medrone - Methylprednisolone",
        "Mefoxin - Cefoxitin",
        "Melleril - Thioridazine",
        "Meptid - Meptazinol",
        "Merbentyl - Dicyclomine hydrochloride/Dicycloverine hydrochloride",
        "Merocet - Cetylpyridinium chloride",
        "Meronem - Meropenem",
        "Methadose - Methadone hydrochloride",
        "Metrogel - Metronidazole",
        "Metrolyl - Metronidazole",
        "Metrotop - Metronidazole",
        "Micardis - Telmisartan",
        "Mictral - Nalidixic acid",
        "Midrid - Isometheptene mucate",
        "Migranal - Dihydroergotamine mesilate",
        "Migril - Ergotamine tartrate",
        "Minocin MR - Minocycline",
        "Mintec - Peppermint oil",
        "Mintezol - Tiabendazole",
        "Mirapexin - Pramipexole",
        "Mistamine - Mizolastine",
        "Mitoxana - Ifosfamide",
        "Mizollen - Mizolastine",
        "Mobic - Meloxicam",
        "Mobiflex - Tenoxicam",
        "Modecate - Fluphenazine hydrochloride",
        "Moditen - Fluphenazine hydrochloride",
        "Mogadon - Nitrazepam",
        "Molipaxin - Trazodone hydrochloride",
        "Monocor - Bisoprolol",
        "Monotrim - Trimethoprim",
        "Monovent - Terbutaline sulphate",
        "Motens - Lacidipine",
        "Motilium - Domperidone",
        "Motipress - Nortriptyline",
        "Motival - Nortriptyline",
        "Movicol - Macrogols",
        "Mucogel - Aluminium hydroxide",
        "Mycobutin - Rifabutin",
        "Myleran - Busulphan",
        "Myotonine - Bethanechol chloride",
        "Mysoline - Primidone",
        "Nalcrom - Sodium cromoglicate",
        "Nalorex - Naltrexone hydrochloride",
        "Naprosyn - Naproxen",
        "Naramig - Naratriptan",
        "Nardil - Phenelzine",
        "Naropin - Ropivacaine",
        "Narphen - Phenazocine",
        "Natrillix - Indapamide",
        "Navelbine - Vinorelbine",
        "Navoban - Tropisetron",
        "Nebcin - Tobramycin",
        "Nebules - Fluticasone",
        "propionate/Salbutamol    431",
        "Negram - Nalidixic acid",
        "Neo-Mercazole - Carbimazole",
        "Neoral - Ciclosporin",
        "Netillin - Netilmicin",
        "Neulactil - Pericyazine",
        "Neurontin - Gabapentin",
        "Neutrexin - Trimetrexate",
        "NiQuitin CQ - Nicotine",
        "Nicorette - Nicotine",
        "Nicotinell - Nicotine",
        "Niferex - Polysaccharide-iron complex",
        "Nimotop - Nimodipine",
        "Nivaquine - Chloroquine",
        "Nivemycin - Neomycin sulphate",
        "Nizoral - Ketoconazole",
        "Nolvadex - Tamoxifen",
        "Nootropil - Piracetam",
        "Norgalax Micro-enema - Docusate sodium",
        "Normacol - Sterculia",
        "Norprolac - Quinagolide",
        "Norvir - Ritonavir",
        "Novantrone - Mitoxantrone",
        "Nozinan - Levomepromazine/ Methotrimeprazine",
        "Nozinan - Methotrimeprazine/ Levomepromazine",
        "Nuelin - Theophylline",
        "Nurofen - Ibuprofen",
        "Nutrizym - Pancreatin",
        "Nystan - Nystatin",
        "Oncovin - Vincristine sulphate",
        "Optimax - Tryptophan",
        "Optimine - Azatadine maleate",
        "OrLAAM - Levacetylmethadol hydrochloride",
        "Oralbalance - Saliva substitute",
        "Oraldene - Hexetidine",
        "Oramorph - Morphine",
        "Orap - Pimozide",
        "Orelox - Cefpodoxime",
        "Orgaran - Danaparoid",
        "Orudis - Ketoprofen",
        "Oxis - Eformoterol fumarate/Formoterol fumarate",
        "Oxivent - Oxitropium bromide",
        "Palfium - Dextromoramide",
        "Palladone - Hydromorphone hydrochloride",
        "Paludrine - Proguanil hydrochloride",
        "Paludrine/Avoclor - Chloroquine",
        "Panadol - Paracetamol",
        "Pancrease - Pancreatin",
        "Pancrex - Pancreatin",
        "Paraplatin - Carboplatin",
        "Pariet - Rabeprazole sodium",
        "Parlodel - Bromocriptine",
        "Parnate - Tranylcypromine",
        "Penbritin - Ampicillin",
        "Penicillin G - Benzyl penicillin",
        "Penicillin V - Phenoxymethyl penicillin",
        "Pentacarinat - Pentamidine isethionate",
        "Pentasa - Mesalazine",
        "Pentostam - Sodium stibogluconate",
        "Pepcid - Famotidine",
        "Peptac - Alginates",
        "Perdix - Moexipril",
        "Periactin - Cyproheptadine hydrochloride",
        "Peroxyl - Hydrogen peroxide mouthwash",
        "Persantin - Dipyridamole",
        "Pharmorubicin - Epirubicin",
        "Phenergan - Promethazine hydrochloride",
        "Phyllocontin Continus - Aminophylline",
        "Physeptone - Methadone hydrochloride",
        "Physiotens - Moxonidine",
        "Piportil Depot - Pipotiazine palmitate",
        "Piriton - Chlorphenamine maleate / Chlorpheniramine maleate",
        "Pitressin - Vasopressin",
        "Plavix - Clopidogrel",
        "Plendil - Felodipine",
        "Plesmet - Ferrous glycine sulphate",
        "Ponstan - Mefenamic acid",
        "Pork Mixtard - Biphasic isophane insulin",
        "Prepulsid - Cisapride",
        "Prescal - Isradipine",
        "Preservex - Aceclofenac",
        "Priadel - Lithium salts",
        "Priadel: Li-Liquid - Lithium salts 432   ",
        "Primacor - Milrinone",
        "Primalan - Mequitazine",
        "Primaxin - Imipenem with cilastatin",
        "Pripsen - Piperazine",
        "Pro Epanutin - Fosphenytoin sodium",
        "Pro-Viron - Mesterolone",
        "Pro-banthine - Propantheline bromide",
        "Prograf - Tacrolimus",
        "Prominal - Methylphenobarbital",
        "Pronestyl - Procainamide",
        "Propaderm - Beclometasone dipropionate",
        "Proscar - Finasteride",
        "Prothiaden - Dosulepin hydrochloride/Dothiepin hydrochloride",
        "Protium - Pantoprazole",
        "Provigil - Modafinil",
        "Prozac - Fluoxetine",
        "Pulmicort - Budesonide",
        "Pulmozyne - Dornase alpha",
        "Puri-Nethol - Mercaptopurine",
        "Pylorid - Ranitidine bismuth citrate",
        "Pyrogastrone - Carbenoxolone sodium",
        "Questran - Cholestyramine",
        "Quinalbarbitone {[Tuinal]}  -Secobarbital",
        "Qvar - Beclometasone dipropionate",
        "Rapitil - Nedocromil sodium",
        "Raxar - Grepafloxacin",
        "Rebetol - Ribavarin",
        "Regulan - Ispaghula husk",
        "Relenza - Zanamivir",
        "Relifex - Nabumetone",
        "Remnos - Nitrazepam",
        "Requip - Ropinirole",
        "Respacal - Tulobuterol hydrochloride",
        "Respontin - Ipratropium bromide",
        "Restandol - Testosterone",
        "Retrovir - Zidovudine",
        "Revanil - Lisuride maleaten",
        "Rheumox - Azapropazone",
        "Ridaura - Auranofin",
        "Rifadin - Rifampicin",
        "Rifater - Rifampicin",
        "Rifinah 150 - Rifampicin",
        "Rifinah 300 - Rifampicin",
        "Rimacid - Indomethacin",
        "Rimactane - Rifampicin",
        "Rimactazid 150 - Rifampicin",
        "Rimactazid 300 - Rifampicin",
        "Rimapam - Diazepam",
        "Risperdal - Risperidone",
        "Ritalin - Methylphenidate hydrochloride",
        "Rivotril - Clonazepam",
        "Robicin - Spectinomycin",
        "Rocephin - Ceftriaxone",
        "Rohypnol - Flunitrazepam",
        "Rotacaps - Salbutamol",
        "Rozex - Metronidazole",
        "Rynacrom. - Sodium cromoglicate",
        "Rythmodan - Disopyramide",
        "Salagen - Pilocarpine hydrochloride",
        "Salazopyrin - Sulfasalazine",
        "Saliva Orthana - Saliva substitute",
        "Salivace - Saliva substitute",
        "Salivix - Saliva substitute",
        "Salofalk - Mesalazine",
        "Saluric - Chlorothiazide",
        "Salveze - Saliva substitute",
        "Sanomigran - Pizotifen",
        "Scandonest - Mepivacaine",
        "Scopoderm - Hyoscine hydrobromide",
        "Sectral - Acebutolol",
        "Securon - Verapamil",
        "Securopen - Azlocillin",
        "Selexid - Pivmecillinam hydrochloride",
        "Semprex - Acrivastine",
        "Senokot - Senna",
        "Septanenst - Articaine",
        "Septrin - Co-trimoxazole",
        "Serc - Betahistine dihydrochloride",
        "Serdolect - Sertindole",
        "Serenace - Haloperidol",
        "Seretide - Fluticasone propionate",
        "Serevent - Salmeterol",
        "Seroquel - Quetiapine",
        "Seroxat - Paroxetine    433",
        "Sinemet CR - Co-careldopa",
        "Sinemet plus - Co-careldopa",
        "Sinemet - Co-careldopa",
        "Sinequan - Doxepin",
        "Singulair - Montelukast",
        "Skelid - Tiludronic acid",
        "Slo-Phyllin - Theophylline",
        "Slozem - Diltiazem",
        "Sno Phenicol - Chloramphenicol",
        "Solfedipine - Nifedipine",
        "Solian - Amisulpride",
        "Solu-cortel - Hydrocortisone",
        "Sonata - Zaleplon",
        "Sotacor - Sotalol hydrochloride",
        "Spiroctan - Spironolactone",
        "Sporanox - Itraconazole",
        "Staril - Fosinopril",
        "Stelazine - Trifluoperazine",
        "Stemetil - Prochlorperazine",
        "Stesolid - Diazepam",
        "Stilboesterol - Diethylstilbestrol",
        "Stilnoct - Zolpidem tartrate",
        "Stromba - Stanozolol",
        "Stugeron - Cinnarizine",
        "Sudafed - Pseudoephedrine hydrochloride",
        "Sulparex - Sulpiride",
        "Sulpitil - Sulpiride",
        "Suprax - Cefixime",
        "Suprecur - Buserelin",
        "Surgam - Tiaprofenic acid",
        "Surmontil - Trimipramine",
        "Sustiva - Efavirenz",
        "Symmetrel - Amantadine hydrochloride",
        "Synagis - Palivizumab",
        "Synercid - Quinupristin with Dalfopristin",
        "Syscor - Nisoldipine",
        "Tagamet - Cimetidine",
        "Tambocor - Flecainide acetate",
        "Tanatril - Imidapril",
        "Targocid - Teicoplanin",
        "Tarivid - Ofloxacin",
        "Tavanic - Levofloxacin",
        "Tavegil - Clemastine",
        "Taxol - Paclitaxel",
        "Taxotere - Docetaxel",
        "Tazocin - Piperacillin",
        "Tegretol retard - Carbamazepine",
        "Tegretol - Carbamazepine",
        "Telfast - Fexofenadine hydrochloride",
        "Temgesic - Buprenorphine",
        "Tenorminx - Atenolol",
        "Tensipine - Nifedipine",
        "Tensium - Diazepam",
        "Terasyl 300 - Lymecycline",
        "Teril CR - Carbamazepine",
        "Terramycin - Oxytetracycline",
        "Tertroxin - Liothyronine sodium",
        "Teveten - Eprosartan",
        "Theo-Dur - Theophylline",
        "Tilade - Nedocromil sodium",
        "Tildiem - Diltiazem",
        "Tiloryth - Erythromycin",
        "Timecef - Cefodizime",
        "Timentin - Ticarcillin",
        "Timonil retard. - Carbamazepine",
        "Tofranil - Imipramine hydrochloride",
        "Tolanase - Tolazamide",
        "Tomudex - Raltitrexed",
        "Topal - Alginates",
        "Topamax - Topiramate",
        "Trandate - Labetalol",
        "Trasicor - Oxprenolol hydrochloride",
        "Trileptal - Oxcarbazepine",
        "Triludan - Terfenadine",
        "Trimopan - Trimethoprim",
        "Triptaphen - Amitriptyline hydrochloride",
        "Tritace - Ramipril",
        "Trusopt - Dorzolamide",
        "Tryptizol - Amitriptyline hydrochloride",
        "Ubretid - Distigmine bromide",
        "Ucerax - Hydroxyzine hydrochloride",
        "Ultralanum - Fluticasone propionate",
        "Uniphyllin Continus - Theophylline",
        "Unisomnia - Nitrazepam",
        "Urdox - Ursodeoxycholic acid",
        "Uriben - Nalidixic acid",
        "Urispass 200 - Flavoxate hydrochloride",
        "Ursofalk - Ursodeoxycholic acid 434   ",
        "Ursogal - Ursodeoxycholic acid",
        "Utinor - Norfloxacin",
        "Valclair - Diazepam",
        "Valium - Diazepam",
        "Vallergan - Alimemazine tartrate/ Trimeprazine tartrate",
        "Valoid - Cyclizine",
        "Valtrex - Valaciclovir",
        "Vancocin - Vancomycin",
        "Vascace - Cilazapril",
        "Velbe - Vinblastine sulphate",
        "Velosef - Cefradine",
        "Ventide - Beclometasone dipropionate",
        "Ventodisks - Salbutamol",
        "Ventolin - Salbutamol",
        "Vepesid - Etoposide",
        "Vermox - Mebendazole",
        "Viagra - Sildenafil",
        "Viazem - Diltiazem",
        "Vibramycin -D - Doxycycline",
        "Vibramycin - Doxycycline",
        "Videx - Didanosine",
        "Vioxx - Rofecoxib",
        "Viracept - Nelfinavir",
        "Viramune - Nevirapine",
        "Virazole - Ribavarin",
        "Visclair - Mecysteine hydrochloride",
        "Visken - Pindolol",
        "Vistide - Cidofovir",
        "Vivalan - Viloxazine hydrochloride",
        "Voltarol - Diclofenac sodium",
        "Welldorm - Chloral hydrate",
        "Wellvone - Atovaquone",
        "Xanax - Alprazolam",
        "Xenical - Orlistat",
        "Xylocaine - Lidocaine/Lignocaine Dental preparations",
        "Xylotox - Lidocaine/Lignocaine Dental preparations",
        "Yomesan - Niclosamide",
        "Zaditen - Ketotifen",
        "Zadstat - Metronidazole",
        "Zamadol - Tramadol hydrochloride",
        "Zandip - Lercanidipine",
        "Zantac - Ranitidine",
        "Zarontin - Ethosuximide",
        "Zavedos - Idarubicin hydrochloride",
        "Zelapar - Selegeline hydrochloride",
        "Zemtard - Diltiazem",
        "Zerit - Stavudine",
        "Zestril - Lisinopril",
        "Ziagen - Abacavir",
        "Zimovane - Zopiclone",
        "Zinacef - Cefuroxime",
        "Zinamide - Pyrazinamide",
        "Zinnat - Cefuroxime",
        "Zirtek - Cetirizine hydrochloride",
        "Zispin - Mirtazapine",
        "Zithromax - Azithromycin",
        "Zocor - Simvastatin",
        "Zofran - Ondansetron",
        "Zoleptil - Zotepine",
        "Zomig - Zolmitriptan",
        "Zoton - Lansoprazole",
        "Zovirax - Aciclovir",
        "Zyban - Amfebutamone",
        "Zydol - Tramadol hydrochloride",
        "Zyloric - Allopurinol",
        "Zyprexa - Olanzapine"
    ];
    $("#txtMedicationName").autocomplete({
        source: medications
    });
});