$(function() {
//                var medications = [
//                    "Accolate  - Zafirlukast",
//                    "Accuhaler  - Salbutamol",
//                    "Accupro  - Quinapril",
//                    "Acepril  - Captopril",
//                    "Acetaminophen  - Paracetamol",
//                    "Achromycin  - Tetracycline",
//                    "Acupan  - Nefopam hydrochloride",
//                    "Adactone  - Spironolactone",
//                    "Adalat  - Nifedipine",
//                    "Adizem  - Diltiazem",
//                    "Adrenaline in dental local anaesthetic solutions  - Epinephrine",
//                    "AeroBec  - Beclometasone dipropionate",
//                    "Aerocrom  - Sodium cromoglicate",
//                    "Aerolin  - Salbutamol",
//                    "Airomir  - Salbutamol",
//                    "Akineton  - Biperiden",
//                    "Aldomet  - Methyldopa",
//                    "Algicon  - Alginates",
//                    "Alkeran  - Melphalan",
//                    "Allegron  - Nortriptyline",
//                    "Alphaparin  - Certoparin",
//                    "Alu-cap  - Aluminium hydroxide",
//                    "Alupent  - Orciprenaline sulphate",
//                    "Alvercol  - Alverine citrate",
//                    "Amaryl  - Glimepiride",
//                    "Ametop  - Amethocaine",
//                    "Amias  - Candesartan",
//                    "Amikin  - Amikacin",
//                    "Amoxil  - Amoxicillin",
//                    "Amylobarbitone  - Amobarbital",
//                    "Anabact  - Metronidazole",
//                    "Anafranil  - Clomipramine hydrochloride",
//                    "Ancotil  - Flucytosine",
//                    "Androcur  - Cyproterone acetate",
//                    "Anexate  - Flumazenil",
//                    "Angiopine  - Nifedipine",
//                    "Angitil  - Diltiazem",
//                    "Anquil  - Benperidol",
//                    "Antabuse  - Disulfiram",
//                    "Antepsin  - Sucralfate",
//                    "Anturan  - Sulfinpyrazone",
//                    "Apresoline  - Hydralazine",
//                    "Aprovel  - Irbesartan",
//                    "Aricept  - Donepezil hydrochloride",
//                    "Arimidex  - Anastrozole",
//                    "Arosmasin  - Exemestan",
//                    "Arpicolin  - Procyclidine hydrochloride",
//                    "Arythmol  - Propafenone hydrochloride",
//                    "Asacol  - Mesalazine",
//                    "Asendis  - Amoxapine",
//                    "AsmaBec  - Beclometasone dipropionate",
//                    "Asmasal  - Salbutamol",
//                    "Aspirin  - Acetylsalicylic acid",
//                    "Atarax  - Hydroxyzine hydrochloride",
//                    "Atrovent  - Ipratropium bromide",
//                    "Augmentin  - Co-amoxiclav",
//                    "Augmentin-Duo  - Co-amoxiclav",
//                    "Avloclor  - Chloroquine",
//                    "Avomine  - Promethazine teoclate",
//                    "Axid  - Nizatidine",
//                    "Azactam  - Aztreonam",
//                    "Azopt  - Brinzolamide"
//                ];
    var medications;
    $.ajax({
        type: 'POST',
        url: "knowledge_profile/loadMedication",
        data: 'id=medication',
        dataType: 'json',
        cache: false,
        success: function(result) {
            medications = result.medications;
            console.log(medications);
        },
    });
    $("#txtMedicationName").autocomplete({
        source: medications
    });
});
